samples: ["sample1"]
raw_reads_dir: "../data/raw"
results_dir: "../results"
contig_min_length: 2000  # Для Megahit, VAMB и PHAMB
threads: 4
phamb_script: "../phamb/phamb/run_RF.py"
vog_db: "../data/db/hmm/vogdb.hmm"
miComplete_db: "../data/db/hmm/miComplete.hmm"
